controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

armies:
    path: /armies
    controller: App\Controller\EjercitoController::armies_list
    methods: ['GET']

army:
    path: /armies/{id}
    controller: App\Controller\EjercitoController::seek_army
    methods: ['GET']


anadir:
    path: /armies
    controller: App\Controller\EjercitoController::add_army
    methods: ['POST']

borrar:
    path: /armies/{raza}
    controller: App\Controller\EjercitoController::delete_army
    methods: ['DELETE']


editar:
    path: /armies/{id}
    controller: App\Controller\EjercitoController::modify_army
    methods: ['PUT']
    requirements: 
        id: \d+

rules:
    path: /rules
    controller: App\Controller\ReglasController::rules_list
    methods: ['GET']

mostrarRegla:
    path: /rules/{nombre}
    controller: App\Controller\ReglasController::seek_rule
    methods: ['GET']

anadirRegla:
    path: /rules
    controller: App\Controller\ReglasController::add_rule
    methods: ['POST']

borrarRegla:
    path: /rules/{nombre}
    controller: App\Controller\ReglasController::delete_rule
    methods: ['DELETE']

editarRegla:
    path: /rules/{id}
    controller: App\Controller\ReglasController::modify_rule
    methods: ['PUT']
    requirements: 
        id: \d+

mostrarAtributos:
    path: /attribute
    controller: App\Controller\AtributosController::attribute_list
    methods: ['GET']


anadirAtributos:
    path: /attribute/{id}
    controller: App\Controller\AtributosController::add_attribute
    methods: ['POST']


borrarAtributos:
    path: /attribute/{id}
    controller: App\Controller\AttributosController::delete_attributes
    methods: ['DELETE']

editarAtributos:
    path: /attribute/{id}
    controller: App\Controller\AtributosController::modify_attributes
    methods: ['PUT']
    requirements: 
        id: \d+

mostrarUsuarios:
    path: /users
    controller: App\Controller\UserController::users_display
    methods: ['GET']

mostrarUsuario:
    path: /users/{id}
    controller: App\Controller\UserController::seek_user
    methods: ['GET']


anadirUsuario:
    path: /users
    controller: App\Controller\UserController::add_user
    methods: ['POST']

loginUsuario:
    path: /login
    controller: App\Controller\UserController::logIn
    methods: ['POST']

borrarUsuario:
    path: /users/{id}
    controller: App\Controller\UserController::delete_user
    methods: ['DELETE']


editarUsuario:
    path: /users/{id}
    controller: App\Controller\UserController::modify_user
    methods: ['PUT']

mostrarUnidades:
    path: /units
    controller: App\Controller\UnidadesController::units_list
    methods: ['GET']

mostrarCG:
    path: /units/{id}/cg
    controller: App\Controller\UnidadesController::get_heroes
    methods: ['GET']

mostrarBasicas:
    path: /units/{id}/basica
    controller: App\Controller\UnidadesController::get_basics
    methods: ['GET']

mostrarEspeciales:
    path: /units/{id}/specials
    controller: App\Controller\UnidadesController::get_especials
    methods: ['GET']

mostrarSingulares:
    path: /units/{id}/rare
    controller: App\Controller\UnidadesController::get_rares
    methods: ['GET']

obtenerCampeon:
    path: /champions/{id_unidad}
    controller: App\Controller\CampeonController::get_champion
    methods: ['GET']

ObtenerMejorasUnidad:
    path: /upgrades/{unitId}
    controller: App\Controller\MejorasController::get_upgradesUnit
    methods: ['GET']

ObtenerMejorasGratuitas:
    path: /upgrades/{unitId}/free
    controller: App\Controller\MejorasController::getHandWeapon
    methods: ['GET']

ObtenerListas:
    path: /listas
    controller: App\Controller\ListasController::getListas
    methods: ['GET']

ObtenerLista:
    path: /listas/{id}
    controller: App\Controller\ListasController::seek_list
    methods: ['GET']

ObtenerListaUsuario:
    path: /listas/user/{userId}
    controller: App\Controller\ListasController::seek_user_list
    methods: ['GET']

AddLista:
    path: /listas
    controller: App\Controller\ListasController::add_list
    methods: ['POST']

BorrarLista:
    path: /listas/{id}
    controller: App\Controller\ListasController::delete_list
    methods: ['DELETE']

ModificarLista:
    path: /listas/{id}
    controller: App\Controller\ListasController::modify_list
    methods: ['PUT']